[2025-05-04T00:00:02.746+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_dataset scheduled__2025-05-03T00:00:00+00:00 [queued]>
[2025-05-04T00:00:02.771+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_dataset scheduled__2025-05-03T00:00:00+00:00 [queued]>
[2025-05-04T00:00:02.772+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-04T00:00:02.842+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_dataset> on 2025-05-03 00:00:00+00:00
[2025-05-04T00:00:02.864+0000] {standard_task_runner.py:60} INFO - Started process 91202 to run task
[2025-05-04T00:00:02.886+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'download_dataset', 'scheduled__2025-05-03T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmp9al_kc2i']
[2025-05-04T00:00:02.896+0000] {standard_task_runner.py:88} INFO - Job 96: Subtask download_dataset
[2025-05-04T00:00:02.966+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-04T00:00:03.066+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline.download_dataset scheduled__2025-05-03T00:00:00+00:00 [running]> on host 3f9fdd6459c9
[2025-05-04T00:00:03.299+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-03T00:00:00+00:00'
[2025-05-04T00:00:03.301+0000] {logging_mixin.py:188} INFO - Dataset already exists at /opt/***/datasets/Diabetes/Diabetes.csv
[2025-05-04T00:00:03.302+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-04T00:00:03.323+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_dataset, execution_date=20250503T000000, start_date=20250504T000002, end_date=20250504T000003
[2025-05-04T00:00:03.398+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-04T00:00:03.494+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
