[2025-05-08T00:00:04.179+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_and_selection.train_random_forest scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T00:00:04.197+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_and_selection.train_random_forest scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T00:00:04.197+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-08T00:00:04.526+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_random_forest> on 2025-05-07 00:00:00+00:00
[2025-05-08T00:00:04.558+0000] {standard_task_runner.py:60} INFO - Started process 4730 to run task
[2025-05-08T00:00:04.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'training_and_selection', 'train_random_forest', 'scheduled__2025-05-07T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline_dag.py', '--cfg-path', '/tmp/tmp1cffral_']
[2025-05-08T00:00:04.578+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask train_random_forest
[2025-05-08T00:00:04.771+0000] {task_command.py:423} INFO - Running <TaskInstance: training_and_selection.train_random_forest scheduled__2025-05-07T00:00:00+00:00 [running]> on host 12febc400abb
[2025-05-08T00:00:05.104+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_and_selection' AIRFLOW_CTX_TASK_ID='train_random_forest' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-07T00:00:00+00:00'
[2025-05-08T00:00:05.121+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-08T00:00:05.126+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-08T00:00:08.119+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:00:08 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-08T00:00:48.236+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:00:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-08T00:00:48.621+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-05-08T00:00:59.406+0000] {logging_mixin.py:188} WARNING - Registered model 'diabetes_model' already exists. Creating a new version of this model...
[2025-05-08T00:00:59.499+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:00:59 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: diabetes_model, version 5
[2025-05-08T00:00:59.499+0000] {logging_mixin.py:188} WARNING - Created version '5' of model 'diabetes_model'.
[2025-05-08T00:00:59.718+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:00:59 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://10.43.101.187:30500/#/experiments/1/runs/ce53b424a0d5457696e66aeb47f6f902.
[2025-05-08T00:00:59.719+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:00:59 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://10.43.101.187:30500/#/experiments/1.
[2025-05-08T00:00:59.747+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-08T00:00:59.776+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=training_and_selection, task_id=train_random_forest, execution_date=20250507T000000, start_date=20250508T000004, end_date=20250508T000059
[2025-05-08T00:00:59.983+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-08T00:01:00.115+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
